/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import algo.RC6;
/**
 *
 * @author Destar
 */
public class dekripFile extends javax.swing.JFrame {
    private final RC6 rc6 = new RC6();

    /**
     * Creates new form dekripFile
     */
    public dekripFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Enkrip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setText("File");

        jLabel3.setText("Pass");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String current = "";
        JFileChooser jfc = null;
        LookAndFeel previousLF = UIManager.getLookAndFeel();
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            jfc = new JFileChooser(current);
            jfc.setDialogTitle("Pilih File");
            UIManager.setLookAndFeel(previousLF);
        }catch (IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException | ClassNotFoundException e) {}
        FileFilter docFilter, docxFilter, xlsFilter, xlsxFilter, txtFilter,pdfFilter, allFilter;
        docFilter = new FileNameExtensionFilter("Word 2003", "doc");
        docxFilter = new FileNameExtensionFilter("Word 2007/2010", "docx");
        xlsFilter = new FileNameExtensionFilter("Excel 2003", "xls");
        xlsxFilter = new FileNameExtensionFilter("Excel 2007/2010", "xlsx");
        txtFilter = new FileNameExtensionFilter("Text Document File","txt");
        pdfFilter = new FileNameExtensionFilter("PDF Document File", "pdf");
        allFilter = new FileNameExtensionFilter("All File", "doc", "docx", "xls", "xlsx", "txt");
        jfc.setAcceptAllFileFilterUsed(false);
        jfc.addChoosableFileFilter(docFilter);
        jfc.addChoosableFileFilter(docxFilter);
        jfc.addChoosableFileFilter(xlsFilter);
        jfc.addChoosableFileFilter(xlsxFilter);
        jfc.addChoosableFileFilter(txtFilter);
        jfc.addChoosableFileFilter(pdfFilter);
        jfc.addChoosableFileFilter(allFilter);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String f = jfc.getSelectedFile().toString();
            jTextField1.setText(f);
        }
        else {
            jfc.hide();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (jTextField1.getText().equals("")){
                JOptionPane.showMessageDialog(this,"File Belum Di Pilih");
                jTextField1.requestFocus();
            }
            else if (jTextField2.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Password Belum Di Masukan");
                jTextField2.requestFocus();
            }
            else{
                //
                long start = System.currentTimeMillis();
                File file = new File(jTextField1.getText());
                FileInputStream fis = new FileInputStream(file);
                byte[] b = new byte[(int) file.length()];
                fis.read(b);

                //byte[]passByte= STB2(password);
                //Encryption rc4 = new Encryption(jTextField1.getText().getBytes());
                byte[] en = rc6.decrypt(b, jTextField2.getText().getBytes());

                String f = file.getName().substring(3, file.getName().length());

                File fout = new File("de_" + file.getName());

                long now = System.currentTimeMillis();

                JFileChooser fileChooser = null;
                LookAndFeel previousLF = UIManager.getLookAndFeel();

                try{
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    fileChooser = new JFileChooser();
                    fileChooser.setSelectedFile(fout);
                    fileChooser.setDialogTitle("Save File Location");
                    UIManager.setLookAndFeel(previousLF);

                    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                        boolean doExport = true;
                        boolean overrideExistingFile = false;

                        String dir = fileChooser.getCurrentDirectory().toString();
                        File destinationFile = new File(fileChooser.getSelectedFile().getName());
                        DataOutputStream out = new DataOutputStream(new FileOutputStream(dir + "/" + destinationFile));

                        ByteArrayOutputStream byteOut = new ByteArrayOutputStream();
                        byteOut.write(en);
                        byteOut.writeTo(out);
                        out.close();

                        if (doExport) {
                        }

                        JOptionPane.showMessageDialog(this, "File " + file.getName() + " Berhasil Di Enkrip\nWaktu Enkrip : " + (now-start)/1000.0 + " Detik");

                        jTextField1.setText("");
                        jTextField2.setText("");

                    }

                }
                catch(IllegalAccessException | UnsupportedLookAndFeelException | InstantiationException | ClassNotFoundException e){}
            }
            jTextField1.setText("");
            jTextField2.setText("");
        }
        catch(IOException ioe) {
            JOptionPane.showMessageDialog(this,"File Yang Dipilih Bukan File Doc, Docx, Xls atau Xlsx");
            jTextField1.setText("");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dekripFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dekripFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dekripFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dekripFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dekripFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
